version: '3.8'

services:
  app:
    restart: always
    build: .
    ports:
      - "3007:3007"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306  # Ensure this matches the MySQL container port
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: dbo
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbo
